spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assembleia?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  kafka:
    bootstrap-servers: 0.0.0.0:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

url:
  validate:
    cpf: https://user-info.herokuapp.com/users

server:
  servlet:
    context-path: /api

springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
    swagger:
      v2:
        path: /documentation/v2/api-docs

topic:
  name: resultado-votacao
